// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvirayumvwkwszejwsci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2aXJheXVtdndrd3N6ZWp3c2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTQwNzYsImV4cCI6MjA3MTQzMDA3Nn0.X28Lko9xtf6OGV3zjxuyHqKu0HRx2Dj0M0iWJngZccU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});